
export const murals = [
  {
    title: "Wheel of Life (Bhavacakra)",
    description: "Ralang Monastery- One of the premium monastery in Sikkim belongs to the Kagyu order of Tibetan Buddhism.Though the one we visited is a new one which is in no doubt one of the most beautiful monastery in terms of architecture, wall Paintings etc.",
    image: "https://raw.githubusercontent.com/harshyadav2810/Sikkim-Monastery-project/main/mon2.jpg",
    hint: "bhavacakra mural",
  },
  {
    title: "Mandala of Avalokiteshvara",
    description: "Sikkim as a land deserves extra attention for the harmonious existence of different cultures and how it all coexists in peace. Amongst other things in Sikkim that deserves special mentions are the numbers of Buddhist Monasteries present there",
    image: "https://raw.githubusercontent.com/harshyadav2810/Sikkim-Monastery-project/main/mon3.jpg",
    hint: "mandala mural",
  },
  {
    title: "Life of the Buddha",
    description: "Pemayangtse Monastery is one of the most famous and beautiful structures in the state of Sikkim, situated near a small town of Pelling,",
    image: "https://raw.githubusercontent.com/harshyadav2810/Sikkim-Monastery-project/main/mon4.jpg",
    hint: "buddha mural",
  },
  {
    title: "Guru Padmasambhava",
    description: "A mural dedicated to the 'Second Buddha,' who is credited with bringing Buddhism to Tibet and Sikkim.",
    image: "https://raw.githubusercontent.com/harshyadav2810/Sikkim-Monastery-project/main/monasteryjpgfinal.jpg",
    hint: "padmasambhava mural",
  },
];

export const artifacts = [
  {
    title: "Phurba Dagger",
    description: "A ritual dagger used in Vajrayana Buddhist ceremonies to subdue demonic forces and clear spiritual obstacles.",
    image: "https://raw.githubusercontent.com/harshyadav2810/Sikkim-Monastery-project/main/sp1.jpeg",
    tags: ["Ritual", "Vajrayana", "Ceremony"],
    hint: "buddhist ritual dagger",
    wikiUrl: "https://en.wikipedia.org/wiki/Phurba",
  },
  {
    title: "Singing Bowl",
    description: "A metal bowl that produces a rich, resonant sound when played, used for meditation and healing.",
    image: "https://raw.githubusercontent.com/harshyadav2810/Sikkim-Monastery-project/main/sp2.jpeg",
    tags: ["Meditation", "Sound", "Healing"],
    hint: "tibetan singing bowl",
    wikiUrl: "https://en.wikipedia.org/wiki/Singing_bowl",
  },
  {
    title: "Thangka Painting",
    description: "A Tibetan Buddhist painting on cotton or silk, typically depicting a deity, scene, or mandala.",
    image: "https://raw.githubusercontent.com/harshyadav2810/Sikkim-Monastery-project/main/sp3.jpeg",
    tags: ["Art", "Painting", "Mandala"],
    hint: "tibetan thangka",
    wikiUrl: "https://en.wikipedia.org/wiki/Thangka",
  },
  {
    title: "Vajra Dorje",
    description: "A symbolic thunderbolt and diamond, representing firmness of spirit and spiritual power.",
    image: "https://raw.githubusercontent.com/harshyadav2810/Sikkim-Monastery-project/main/sp4.jpeg",
    tags: ["Symbol", "Power", "Vajrayana"],
    hint: "vajra",
    wikiUrl: "https://en.wikipedia.org/wiki/Vajra",
  },
  {
    title: "Prayer Wheel",
    description: "A cylindrical wheel on a spindle, containing mantras. Spinning it is believed to have the same merit as reciting the mantra.",
    image: "https://raw.githubusercontent.com/harshyadav2810/Sikkim-Monastery-project/main/sp5.jpeg",
    tags: ["Ritual", "Mantra", "Prayer"],
    hint: "tibetan prayer wheel",
    wikiUrl: "https://en.wikipedia.org/wiki/Prayer_wheel",
  },
  {
    title: "Ghanta (Bell)",
    description: "A ritual bell representing wisdom, often used in conjunction with the vajra (thunderbolt).",
    image: "https://raw.githubusercontent.com/harshyadav2810/Sikkim-Monastery-project/main/sp6.jpeg",
    tags: ["Ritual", "Wisdom", "Instrument"],
    hint: "buddhist ritual bell",
    wikiUrl: "https://en.wikipedia.org/wiki/Ghanta",
  },
  {
    title: "Manjushri Statue",
    description: "A statue of the Bodhisattva Manjushri, symbolizing transcendent wisdom. Found in many of Sikkim's monasteries.",
    image: "https://raw.githubusercontent.com/harshyadav2810/Sikkim-Monastery-project/main/sp7.jpeg",
    tags: ["Deity", "Statue", "Wisdom"],
    hint: "bodhisattva statue",
    wikiUrl: "https://en.wikipedia.org/wiki/Manjushri",
  },
  {
    title: "Butter Lamp",
    description: "A traditional lamp fueled by clarified butter, representing the light of wisdom and the removal of ignorance.",
    image: "https://raw.githubusercontent.com/harshyadav2810/Sikkim-Monastery-project/main/sp8.jpeg",
    tags: ["Ritual", "Symbol", "Light"],
    hint: "buddhist butter lamp",
    wikiUrl: "https://en.wikipedia.org/wiki/Butter_lamp",
  },
];

export const manuscripts = [
  {
    title: "Prajnaparamita Sutra",
    description: "A foundational Mahayana scripture on the 'Perfection of Wisdom,' a key text found in Sikkim's monastic libraries.",
    image: "https://raw.githubusercontent.com/harshyadav2810/Sikkim-Monastery-project/main/s1.jpeg",
    tags: ["Mahayana", "Sutra", "Wisdom"],
    hint: "ancient buddhist text",
    wikiUrl: "https://en.wikipedia.org/wiki/Prajnaparamita",
  },
  {
    title: "The Life of Milarepa",
    description: "The biography of the famous Tibetan yogi Milarepa, detailing his path to enlightenment. Highly revered in the Kagyu lineage of Sikkim.",
    image: "https://raw.githubusercontent.com/harshyadav2810/Sikkim-Monastery-project/main/s2.jpeg",
    tags: ["Biography", "Yogi", "Poetry"],
    hint: "tibetan buddhist manuscript",
    wikiUrl: "https://en.wikipedia.org/wiki/Milarepa",
  },
  {
    title: "Bardo Thödol",
    description: "Known as 'The Tibetan Book of the Dead,' this sacred text is a guide for the consciousness after death, a central practice in Nyingma Buddhism in Sikkim.",
    image: "https://raw.githubusercontent.com/harshyadav2810/Sikkim-Monastery-project/main/s3.jpeg",
    tags: ["Vajrayana", "Afterlife", "Guide"],
    hint: "sacred scroll",
    wikiUrl: "https://en.wikipedia.org/wiki/Bardo_Thodol",
  },
  {
    title: "Sikkim Chronicles",
    description: "A collection of royal histories and chronicles detailing the lineage of the Namgyal dynasty and the kingdom's founding.",
    image: "https://raw.githubusercontent.com/harshyadav2810/Sikkim-Monastery-project/main/s4.jpeg",
    tags: ["History", "Chronicle", "Kingdom"],
    hint: "historical document",
    wikiUrl: "https://en.wikipedia.org/wiki/History_of_Sikkim",
  },
  {
    title: "Kangyur Collection",
    description: "Part of the Tibetan Buddhist canon, containing the translated words of the Buddha. The volumes are kept in the monasteries of Sikkim.",
    image: "https://raw.githubusercontent.com/harshyadav2810/Sikkim-Monastery-project/main/s5.jpeg",
    tags: ["Canon", "Buddha's Teachings", "Collection"],
    hint: "buddhist canon",
    wikiUrl: "https://en.wikipedia.org/wiki/Kangyur",
  },
  {
    title: "Lhatsun Chenpo's Biography",
    description: "The biography of Lhatsun Chenpo, one of the three lamas who consecrated the first king of Sikkim, a key figure in the region's spiritual history.",
    image: "https://raw.githubusercontent.com/harshyadav2810/Sikkim-Monastery-project/main/s6.jpeg",
    tags: ["Founders", "Biography", "Lamas"],
    hint: "spiritual history",
    wikiUrl: "https://en.wikipedia.org/wiki/Lhats%C3%BCn_Namkha_Jikm%C3%A9",
  },
  {
    title: "Dzogchen Teachings",
    description: "Texts related to the 'Great Perfection' tradition, a core practice of the Nyingma school prevalent in Sikkim's monasteries.",
    image: "https://raw.githubusercontent.com/harshyadav2810/Sikkim-Monastery-project/main/s7.jpeg",
    tags: ["Dzogchen", "Nyingma", "Tantra"],
    hint: "great perfection text",
    wikiUrl: "https://en.wikipedia.org/wiki/Dzogchen",
  },
  {
    title: "Lepcha Manuscripts",
    description: "A collection of ancient texts in the unique Lepcha script, detailing their history, traditions, and shamanistic practices.",
    image: "https://raw.githubusercontent.com/harshyadav2810/Sikkim-Monastery-project/main/s8.jpeg",
    tags: ["Lepcha", "Indigenous", "Culture"],
    hint: "lepcha script",
    wikiUrl: "https://en.wikipedia.org/wiki/Lepcha_language",
  },
];
